<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageBookingFormLand2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('page_booking_form_land2s')->insert([
            "Lithuania" => "Lithuania",
            "Luxembourg" => "Luxembourg",
            "Macau" => "Macau",
            "Macedonia" => "Macedonia",
            "Madagascar" => "Madagascar",
            "Malaysia" => "Malaysia",
            "Malawi" => "Malawi",
            "Maldives" => "Maldives",
            "Mali" => "Mali",
            "Malta" => "Malta",
            "Marshall_Islands" => "Marshall Islands",
            "Martinique" => "Martinique",
            "Mauritania" => "Mauritania",
            "Mauritius" => "Mauritius",
            "Mayotte" => "Mayotte",
            "Mexico" => "Mexico",
            "Midway_Islands" => "Midway Islands",
            "Moldova" => "Moldova",
            "Monaco" => "Monaco",
            "Mongolia" => "Mongolia",
            "Montserrat" => "Montserrat",
            "Morocco" => "Morocco",
            "Mozambique" => "Mozambique",
            "Myanmar" => "Myanmar",
            "Nambia" => "Nambia",
            "Nauru" => "Nauru",
            "Nepal" => "Nepal",
            "Netherland_Antilles" => "Netherland Antilles",
            "Netherlands" => "Netherlands",
            "Nevis" => "Nevis",
            "New_Caledonia" => "New Caledonia",
            "New_Zealand" => "New Zealand",
            "Nicaragua" => "Nicaragua",
            "Niger" => "Niger",
            "Nigeria" => "Nigeria",
            "Niue" => "Niue",
            "Norfolk_Island" => "Norfolk Island",
            "Norway" => "Norway",
            "Oman" => "Oman",
            "Pakistan" => "Pakistan",
            "Palau_Island" => "Palau Island",
            "Palestine" => "Palestine",
            "Panama" => "Panama",
            "Papua_New_Guinea" => "Papua New Guinea",
            "Paraguay" => "Paraguay",
            "Peru" => "Peru",
            "Phillipines" => "Phillipines",
            "Pitcairn_Island" => "Pitcairn Island",
            "Poland" => "Poland",
            "Portugal" => "Portugal",
            "Puerto_Rico" => "Puerto Rico",
            "Qatar" => "Qatar",
            "Republic_of_Montenegro" => "Republic of Montenegro",
            "Republic_of_Serbia" => "Republic of Serbia",
            "Reunion" => "Reunion",
            "Romania" => "Romania",
            "Russia" => "Russia",
            "Rwanda" => "Rwanda",
            "St_Barthelemy" => "St Barthelemy",
            "St_Eustatius" => "St Eustatius",
            "St_Helena" => "St Helena",
            "St_Kitts_Nevis" => "St Kitts-Nevis",
            "St_Lucia" => "St Lucia",
            "St_Maarten" => "St Maarten",
            "St_Pierre_Miquelon" => "St Pierre & Miquelon",
            "St_Vincent_Grenadines" => "St Vincent & Grenadines",
            "Saipan" => "Saipan",
            "Samoa" => "Samoa",
            "Samoa_American" => "Samoa American",
            "San_Marino" => "San Marino",
            "Sao_Tome_Principe" => "Sao Tome & Principe",
            "Saudi_Arabia" => "Saudi Arabia",
            "Senegal" => "Senegal",
            "Serbia" => "Serbia",
            "Seychelles" => "Seychelles",
            "Sierra_Leone" => "Sierra Leone",
            "Singapore" => "Singapore",
            "Slovakia" => "Slovakia",
            "Slovenia" => "Slovenia",
            "Solomon_Islands" => "Solomon Islands",
            "Somalia" => "Somalia",
            "South_Africa" => "South Africa",
            "Spain" => "Spain",
            "Sri_Lanka" => "Sri Lanka",
            "Sudan" => "Sudan",
            "Suriname" => "Suriname",
            "Swaziland" => "Swaziland",
            "Sweden" => "Sweden",
            "Switzerland" => "Switzerland",
            "Syria" => "Syria",
            "Tahiti" => "Tahiti",
            "Taiwan" => "Taiwan",
            "Tajikistan" => "Tajikistan",
            "Tanzania" => "Tanzania",
            "Thailand" => "Thailand",
            "Togo" => "Togo",
            "Tokelau" => "Tokelau",
            "Tonga" => "Tonga",
            "Trinidad_Tobago" => "Trinidad & Tobago",
            "Tunisia" => "Tunisia",
            "Turkey" => "Turkey",
            "Turkmenistan" => "Turkmenistan",
            "Turks_Caicos_Is" => "Turks & Caicos Is",
            "Tuvalu" => "Tuvalu",
            "Uganda" => "Uganda",
            "Ukraine" => "Ukraine",
            "United_Arab_Erimates" => "United Arab Erimates",
            "United_Kingdom" => "United Kingdom",
            "United_States_of_America" => "United States of America",
            "Uraguay" => "Uraguay",
            "Uzbekistan" => "Uzbekistan",
            "Vanuatu" => "Vanuatu",
            "Vatican_City_State" => "Vatican City State",
            "Venezuela" => "Venezuela",
            "Vietnam" => "Vietnam",
            "Virgin_Islands_Brit" => "Virgin Islands (Brit)",
            "Virgin_Islands_USA" => "Virgin Islands (USA)",
            "Wake_Island" => "Wake Island",
            "Wallis_Futana_Is" => "Wallis & Futana Is",
            "Yemen" => "Yemen",
            "Zaire" => "Zaire",
            "Zambia" => "Zambia",
            "Zimbabwe" => "Zimbabwe",
        ]);
    }
}
