<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageBookingFormLandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('page_booking_form_lands')->insert([
            "Afganistan" => "Afganistan",
            "Albania" => "Albania",
            "Algeria" => "Algeria",
            "American_Samoa" => "American Samoa",
            "Andorra" => "Andorra",
            "Angola" => "Angola",
            "Anguilla" => "Anguilla",
            "Antigua_Barbuda" => "Antigua & Barbuda",
            "Argentina" => "Argentina",
            "Armenia" => "Armenia",
            "Aruba" => "Aruba",
            "Australia" => "Australia",
            "Austria" => "Austria",
            "Azerbaijan" => "Azerbaijan",
            "Bahamas" => "Bahamas",
            "Bahrain" => "Bahrain",
            "Bangladesh" => "Bangladesh",
            "Barbados" => "Barbados",
            "Belarus" => "Belarus",
            "Belgium" => "Belgium",
            "Belize" => "Belize",
            "Benin" => "Benin",
            "Bermuda" => "Bermuda",
            "Bhutan" => "Bhutan",
            "Bolivia" => "Bolivia",
            "Bonaire" => "Bonaire",
            "Bosnia_Herzegovina" => "Bosnia & Herzegovina",
            "Botswana" => "Botswana",
            "Brazil" => "Brazil",
            "British_Indian_Ocean_Ter" => "British Indian Ocean Ter",
            "Brunei" => "Brunei",
            "Bulgaria" => "Bulgaria",
            "Burkina_Faso" => "Burkina Faso",
            "Burundi" => "Burundi",
            "Cambodia" => "Cambodia",
            "Cameroon" => "Cameroon",
            "Canada" => "Canada",
            "Canary_Islands" => "Canary Islands",
            "Cape_Verde" => "Cape Verde",
            "Cayman_Islands" => "Cayman Islands",
            "Central_African_Republic" => "Central African Republic",
            "Chad" => "Chad",
            "Channel_Islands" => "Channel Islands",
            "Chile" => "Chile",
            "China" => "China",
            "Christmas_Island" => "Christmas Island",
            "Cocos_Island" => "Cocos Island",
            "Colombia" => "Colombia",
            "Comoros" => "Comoros",
            "Congo" => "Congo",
            "Cook_Islands" => "Cook Islands",
            "Costa_Rica" => "Costa Rica",
            "Cote_DIvoire" => "Cote DIvoire",
            "Croatia" => "Croatia",
            "Cuba" => "Cuba",
            "Curaco" => "Curaco",
            "Cyprus" => "Cyprus",
            "Czech_Republic" => "Czech Republic",
            "Denmark" => "Denmark",
            "Djibouti" => "Djibouti",
            "Dominica" => "Dominica",
            "Dominican_Republic" => "Dominican Republic",
            "East_Timor" => "East Timor",
            "Ecuador" => "Ecuador",
            "Egypt" => "Egypt",
            "El_Salvador" => "El Salvador",
            "Equatorial_Guinea" => "Equatorial Guinea",
            "Eritrea" => "Eritrea",
            "Estonia" => "Estonia",
            "Ethiopia" => "Ethiopia",
            "Falkland_Islands" => "Falkland Islands",
            "Faroe_Islands" => "Faroe Islands",
            "Fiji" => "Fiji",
            "Finland" => "Finland",
            "France" => "France",
            "French_Guiana" => "French Guiana",
            "French_Polynesia" => "French Polynesia",
            "French_Southern_Ter" => "French Southern Ter",
            "Gabon" => "Gabon",
            "Gambia" => "Gambia",
            "Georgia" => "Georgia",
            "Germany" => "Germany",
            "Ghana" => "Ghana",
            "Gibraltar" => "Gibraltar",
            "Great_Britain" => "Great Britain",
            "Greece" => "Greece",
            "Greenland" => "Greenland",
            "Grenada" => "Grenada",
            "Guadeloupe" => "Guadeloupe",
            "Guam" => "Guam",
            "Guatemala" => "Guatemala",
            "Guinea" => "Guinea",
            "Guyana" => "Guyana",
            "Haiti" => "Haiti",
            "Hawaii" => "Hawaii",
            "Honduras" => "Honduras",
            "Hong_Kong" => "Hong Kong",
            "Hungary" => "Hungary",
            "Iceland" => "Iceland",
            "India" => "India",
            "Indonesia" => "Indonesia",
            "Iran" => "Iran",
            "Iraq" => "Iraq",
            "Ireland" => "Ireland",
            "Isle_of_Man" => "Isle of Man",
            "Israel" => "Israel",
            "Italy" => "Italy",
            "Jamaica" => "Jamaica",
            "Japan" => "Japan",
            "Jordan" => "Jordan",
            "Kazakhstan" => "Kazakhstan",
            "Kenya" => "Kenya",
            "Kiribati" => "Kiribati",
            "Korea_North" => "Korea North",
            "Korea_Sout" => "Korea Sout",
            "Kuwait" => "Kuwait",
            "Kyrgyzstan" => "Kyrgyzstan",
            "Laos" => "Laos",
            "Latvia" => "Latvia",
            "Lebanon" => "Lebanon",
            "Lesotho" => "Lesotho",
            "Liberia" => "Liberia",
            "Libya" => "Libya",
            "Liechtenstein" => "Liechtenstein",
            
        ]);
    }
}
