<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('room_reviews')->insert([
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Marlene Simpson',
                'review_date' => 'February 03, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quis rem esse quaerat eius labore repellendus, odit officia, quas provident reprehenderit magnam adipisci inventore quibusdam est architecto nisi.',
                'room_id' => 1,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Brad Knight',
                'review_date' => 'January 17, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium omnis, eius impedit cum. Necessitatibus illum veritatis, consequatur quia itaque tenetur recusandae nostrum quod aperiam.',
                'room_id' => 1,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Daryl Phillips',
                'review_date' => 'August 16, 2017',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim id, facere porro. Ipsum quia maxime atque adipisci inventore dolor nesciunt, molestias voluptatum, ab dignissimos! Alias.',
                'room_id' => 1,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '3',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Maaaaaaaaarlene Simpson',
                'review_date' => 'February 03, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quis rem esse quaerat eius labore repellendus, odit officia, quas provident reprehenderit magnam adipisci inventore quibusdam est architecto nisi.',
                'room_id' => 2,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '4',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Braaaaaaaaaaad Knight',
                'review_date' => 'January 17, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium omnis, eius impedit cum. Necessitatibus illum veritatis, consequatur quia itaque tenetur recusandae nostrum quod aperiam.',
                'room_id' => 2,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '1',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Daaaaaaaaaaaryl Phillips',
                'review_date' => 'August 16, 2017',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim id, facere porro. Ipsum quia maxime atque adipisci inventore dolor nesciunt, molestias voluptatum, ab dignissimos! Alias.',
                'room_id' => 2,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '3',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Maaaaaaaaarlene Simpson',
                'review_date' => 'February 03, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quis rem esse quaerat eius labore repellendus, odit officia, quas provident reprehenderit magnam adipisci inventore quibusdam est architecto nisi.',
                'room_id' => 2,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Braaaaaaaaaaad Knight',
                'review_date' => 'January 17, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium omnis, eius impedit cum. Necessitatibus illum veritatis, consequatur quia itaque tenetur recusandae nostrum quod aperiam.',
                'room_id' => 2,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '1',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Daaaaaaaaaaaryl Phillips',
                'review_date' => 'August 16, 2017',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim id, facere porro. Ipsum quia maxime atque adipisci inventore dolor nesciunt, molestias voluptatum, ab dignissimos! Alias.',
                'room_id' => 2,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '3',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Maaaaaaaaarlene Simpson',
                'review_date' => 'February 03, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quis rem esse quaerat eius labore repellendus, odit officia, quas provident reprehenderit magnam adipisci inventore quibusdam est architecto nisi.',
                'room_id' => 3,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Braaaaaaaaaaad Knight',
                'review_date' => 'January 17, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium omnis, eius impedit cum. Necessitatibus illum veritatis, consequatur quia itaque tenetur recusandae nostrum quod aperiam.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '1',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Daaaaaaaaaaaryl Phillips',
                'review_date' => 'August 16, 2017',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim id, facere porro. Ipsum quia maxime atque adipisci inventore dolor nesciunt, molestias voluptatum, ab dignissimos! Alias.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '3',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Maaaaaaaaarlene Simpson',
                'review_date' => 'February 03, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quis rem esse quaerat eius labore repellendus, odit officia, quas provident reprehenderit magnam adipisci inventore quibusdam est architecto nisi.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Braaaaaaaaaaad Knight',
                'review_date' => 'January 17, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium omnis, eius impedit cum. Necessitatibus illum veritatis, consequatur quia itaque tenetur recusandae nostrum quod aperiam.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '1',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Daaaaaaaaaaaryl Phillips',
                'review_date' => 'August 16, 2017',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim id, facere porro. Ipsum quia maxime atque adipisci inventore dolor nesciunt, molestias voluptatum, ab dignissimos! Alias.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '3',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Maaaaaaaaarlene Simpson',
                'review_date' => 'February 03, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quis rem esse quaerat eius labore repellendus, odit officia, quas provident reprehenderit magnam adipisci inventore quibusdam est architecto nisi.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Braaaaaaaaaaad Knight',
                'review_date' => 'January 17, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium omnis, eius impedit cum. Necessitatibus illum veritatis, consequatur quia itaque tenetur recusandae nostrum quod aperiam.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '1',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Daaaaaaaaaaaryl Phillips',
                'review_date' => 'August 16, 2017',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim id, facere porro. Ipsum quia maxime atque adipisci inventore dolor nesciunt, molestias voluptatum, ab dignissimos! Alias.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '3',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Maaaaaaaaarlene Simpson',
                'review_date' => 'February 03, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum quis rem esse quaerat eius labore repellendus, odit officia, quas provident reprehenderit magnam adipisci inventore quibusdam est architecto nisi.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '5',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Braaaaaaaaaaad Knight',
                'review_date' => 'January 17, 2018',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium omnis, eius impedit cum. Necessitatibus illum veritatis, consequatur quia itaque tenetur recusandae nostrum quod aperiam.',
                'room_id' => 4,
            ],
            [
                'userImage_img' => 'admin.jpg',
                'rating' => '3',
                'rating_i_class' => 'fa-star',
                'review_info' => 'Daaaaaaaaaaaryl Phillips',
                'review_date' => 'August 16, 2017',
                'review_location' => 'Madrid / Spain',
                'review_text' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim id, facere porro. Ipsum quia maxime atque adipisci inventore dolor nesciunt, molestias voluptatum, ab dignissimos! Alias.',
                'room_id' => 4,
            ],
        ]);
    }
}
