@extends('front.layout.main')
@section('content')
  @include('front.partials.layout.top-menu')
  @include('front.partials.layout.header')
  @include('front.partials.pages.staff.page-title')
  @include('front.partials.pages.staff.staff')
  @include('front.partials.layout.footer')
@endsection
@section('after-wrapper')
  @include('front.partials.layout.notification')
@endsection
